# Generated by Django 4.2.10 on 2024-02-27 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Start', '0002_alter_work_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name_plural': 'Work'},
        ),
    ]
