# Generated by Django 4.2.10 on 2024-02-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Start', '0003_alter_work_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideosWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='videos_uploaded')),
            ],
            options={
                'verbose_name_plural': 'Video work',
            },
        ),
        migrations.RenameModel(
            old_name='Work',
            new_name='ImagesWork',
        ),
        migrations.AlterModelOptions(
            name='imageswork',
            options={'verbose_name_plural': 'Image work'},
        ),
    ]
