# Generated by Django 4.2.10 on 2024-02-27 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Start', '0004_videoswork_rename_work_imageswork_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoswork',
            old_name='image',
            new_name='video',
        ),
    ]
