# Generated by Django 4.2.10 on 2024-03-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Start', '0005_rename_image_videoswork_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images_uploaded')),
            ],
            options={
                'verbose_name_plural': 'Service',
            },
        ),
    ]
